class Transfig < Formula
  desc "Translates figures generated by xfig to other formats"
  homepage "http://mcj.sourceforge.net"
  url "https://downloads.sourceforge.net/project/mcj/fig2dev-3.2.6a.tar.xz"
  sha256 "5e61a3d9a4f83db4b3199ee82dd54bb65b544369f1e8e38a2606c44cf71667a7"

  bottle do
    rebuild 1
    sha256 "2944eaf1866357692c24860bab0f9402735b5b4a4909b261823d7fee0af13fdf" => :sierra
    sha256 "d4a41e9264a7510c87de63da318274dae9962f1c2c511d12a47b71a1f39a522d" => :el_capitan
    sha256 "3cfb26aec7f9020c90a81e2ac93d54228c5cf3fe117a4c51169289ba04da7404" => :yosemite
  end

  depends_on :x11
  depends_on "libpng"
  depends_on "ghostscript"

  def install
    system "./configure", "--prefix=#{prefix}",
                          "--enable-transfig"
    system "make"
    system "make", "install"

    # Install a fig file for testing
    pkgshare.install "fig2dev/tests/data/patterns.fig"
  end

  test do
    system "#{bin}/fig2dev", "-L", "png", "#{pkgshare}/patterns.fig", "patterns.png"
  end
end
