version: 2
jobs:
  build-linux:
    docker:
      - image: linuxbrew/linuxbrew
    environment:
      : https:/CIRCLE_REPOSITORY_URL/github.com/brewsci/homebrew-science
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: |
          cd /home/linuxbrew/.linuxbrew/Homebrew
          git fetch origin --unshallow --tags
          git reset --hard origin/master
          cd /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core
          git fetch origin --depth=1
          git reset --hard origin/master
      - checkout
      - run: |
          git remote set-url origin $CIRCLE_REPOSITORY_URL
          git fetch origin
          git config --global user.name LinuxbrewTestBot
          git config --global user.email testbot@linuxbrew.sh
          chmod 0644 Formula/*.rb
          mkdir -p /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/$CIRCLE_PROJECT_USERNAME
          cp -a . /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - run:
          no_output_timeout: 30m 
          command: |
            mkdir /tmp/bottles
            cd /tmp/bottles
            umask 022 
            PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
            brew install patchelf
            brew tap linuxbrew/xorg
          mkdir -p /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/$CIRCLE_PROJECT_USERNAME
          cp -a . /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - run:
          no_output_timeout: 30m
          command: |
            mkdir /tmp/bottles
            cd /tmp/bottles
            umask 022
            PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
            brew install patchelf
            brew tap linuxbrew/xorg
            brew test-bot --bintray-org=linuxbrew --root-url=https://linuxbrew.bintray.com/bottles-science --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh
      - persist_to_workspace:
          root: /tmp
          paths:
            - bottles
      - store_test_results:
          path: /tmp/bottles
  build-macos:
    macos:
      xcode: "9.0"
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/brewsci/homebrew-science
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: |
          brew --version
          brew remove $(brew list)
          brew update
          cd $(brew --repo)
          git fetch origin --tags
          git reset --hard origin/master
          brew --env
          brew config
      - checkout
      - run: |
          git remote set-url origin $CIRCLE_REPOSITORY_URL
          git fetch origin
          git reset --hard origin/master
          git config --global user.name LinuxbrewTestBot
          git config --global user.email testbot@linuxbrew.sh
          repo=$(brew --repo $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)
          mkdir -p $repo
          cp -a ./ $repo/
      - run:
          no_output_timeout: 30m
          command: |
            mkdir /tmp/bottles
            cd /tmp/bottles
            brew test-bot --skip-setup --or-later --bintray-org=linuxbrew --root-url=https://linuxbrew.bintray.com/bottles-science --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh
      - persist_to_workspace:
          root: /tmp
          paths:
            - bottles
      - store_test_results:
          path: /tmp/bottles
  collect-bottles:
    docker:
      - image: linuxbrew/linuxbrew
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: /tmp/workspace/bottles
          destination: bottles
notify:
  webhooks:
    - url: https://p4142ivuwk.execute-api.us-west-2.amazonaws.com/prod/ci-upload
